---
# tasks file for sensu

- import_tasks: common.yml

- import_tasks: server.yml
  when: sensu_install_server

- import_tasks: uchiwa.yml
  when: sensu_install_server and sensu_install_uchiwa

- import_tasks: client.yml
  when: sensu_install_client
